// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovqzhrseppxmbtxkcxtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cXpocnNlcHB4bWJ0eGtjeHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MTg2ODIsImV4cCI6MjA4OTE5NDY4Mn0.CFtWVB5yF6bZeOwgsFGLTDlr5w6O16lR7D_HXuM4EBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});